### PR TITLE
chore: rename the tutor-multi references to harmony

### LINKED ISSUE #18: Adjusting the references to tutor-multi
Now that we have a *much nicer* name for the project we should go ahead and change all the files/references to `tutor-multi` across the repo, for example:

- [The chart](https://github.com/openedx/openedx-k8s-harmony/tree/main/tutor-multi-chart)
- [The plugin](https://github.com/openedx/openedx-k8s-harmony/tree/main/tutor-contrib-multi-plugin)
- [Some variables](https://github.com/openedx/openedx-k8s-harmony/blob/main/tutor-contrib-multi-plugin/tutor_multi_k8s_plugin/plugin.py#L19)
- etc

### PR DESCRIPTION
**Pull request by MoisesGSalas**
# Description

This changes all the previous references to the `tutor-multi` placeholder name to `harmony`. I opted to use only "harmony" in everything related to the chart and "k8s_harmony" for the references in the tutor plugin code.

closes #18

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @MoisesGSalas!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by bradenmacdonald — APPROVED** [review]
Thanks @MoisesGSalas !

I haven't been able to test this yet but the changes look great.

**Comment by bradenmacdonald** [comment]
I tested this today and confirmed that the helm chart installs into the cluster, and the plugin installs into the Tutor environment. Thanks @MoisesGSalas, great work!

**Comment by openedx-webhooks** [comment]
@MoisesGSalas 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-k8s-harmony&entry.867055334=https://github.com/openedx/openedx-k8s-harmony/pull/27&entry.1484655318=https://github.com/MoisesGSalas&entry.752974735=2023-04-01+03:02&entry.1917517419=2023-04-07+16:35&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
