### PR TITLE
[CLOSED] Implementing releases for the harmony Helm Chart

### PR DESCRIPTION
**Pull request by jfavellar90**
This PR aims to implement the [chart-releaser action](https://github.com/helm/chart-releaser-action) to handle the releases of the harmony chart, hosting it in GitHub Pages. This PR implies the following changes in this repo:

- The harmony chart was moved to a folder called `charts`, which complies with the chart-releaser standard.
- The `gh-pages` branch was pushed to the repo. This branch will host the README of the repo and an `index.yaml` file containing harmony chart helpful metadata to install the chart with helm. This `index.yaml` file is auto-generated by the chart-releaser action, so it will exist once the first release is run.
- Repo configuration was changed to build GitHub pages from the `gh-pages` branch, as indicated in the chart-releaser [prerequisites](https://github.com/helm/chart-releaser-action#pre-requisites). The page is already available at https://openedx.github.io/openedx-k8s-harmony/
- A GitHub Action was added to run the chart release routine. This action will be run only if changes in the charts are detected.

If this is merged, operators would be able to add the helm repo and install the chart like this:

```
helm repo add openedx-harmony https://openedx.github.io/openedx-k8s-harmony
helm repo update
helm install [RELEASE_NAME] openedx-harmony/harmony-chart
```

### CODE REVIEW

**Review by bradenmacdonald — APPROVED** [review]
Looks good to me. Can you temporarily make this so it runs on PRs too, so that we can see the release and test it before merging?

**Comment by itsjeyd** [comment]
Hey @jfavellar90, a friendly reminder to follow up on @bradenmacdonald's comment above.

**Comment by jfavellar90** [comment]
Closed on behalf of https://github.com/openedx/openedx-k8s-harmony/pull/40

**Comment by openedx-webhooks** [comment]
@jfavellar90 Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-k8s-harmony&entry.867055334=https://github.com/openedx/openedx-k8s-harmony/pull/36&entry.1484655318=https://github.com/jfavellar90&entry.752974735=2023-05-16+16:45&entry.1917517419=2023-06-13+16:31&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
