### PR TITLE
Add __init__.py to harmony_search

### PR DESCRIPTION
**Pull request by mtyaka**
Without this, the module does not get installed correctly when installing the package with pip.

**Test instructions**:

1. Create a fresh virtual environment.
2. Install harmony plugin without this patch: `pip install "git+https://github.com/openedx/openedx-k8s-harmony.git@harmony-chart-0.5.1#egg=tutor-contrib-harmony-plugin&subdirectory=tutor-contrib-harmony-plugin"`
3. Start the python interpreter and try to import the `harmony_search` module: `from tutor_k8s_harmony_plugin.harmony_search.base import BaseSearchAPI`; you will get an import error
4. Uninstall the plugin and re-install a version with this patch: `pip uninstall -y tutor-contrib-harmony-plugin && pip install "git+https://github.com/open-craft/openedx-k8s-harmony.git@mtyaka/add-init-files#egg=tutor-contrib-harmony-plugin&subdirectory=tutor-contrib-harmony-plugin"`
5. Run the python interpreter again and verify that you can successfully import the module this time: `from tutor_k8s_harmony_plugin.harmony_search.base import BaseSearchAPI`

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @mtyaka! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by gabor-boros — CHANGES_REQUESTED** [review]
@mtyaka Could you please bump the version number in the `__about__.py`?

https://github.com/openedx/openedx-k8s-harmony/blob/main/tutor-contrib-harmony-plugin/tutor_k8s_harmony_plugin/__about__.py#L1

**Comment by mtyaka** [comment]
> @mtyaka Could you please bump the version number in the `__about__.py`?

@gabor-boros Done. I set it to `0.5.1` to match the value in [Chart.yaml](https://github.com/openedx/openedx-k8s-harmony/blob/63542c9164c177c2224e912df99df09b8ea34eb7/charts/harmony-chart/Chart.yaml#L8).

**Review by gabor-boros — APPROVED** [review]
@mtyaka I updated the version number to be `0.2.0` instead of `0.5.1`. Although I see the point of having matching version numbers, the plugin is basically separate from the chart, it is just shipped in the same repo as the chart. I'm going to quickly approve and merge this change, so we reduce the back and forth.

**Comment by openedx-webhooks** [comment]
@mtyaka 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-k8s-harmony&entry.867055334=https://github.com/openedx/openedx-k8s-harmony/pull/67&entry.1484655318=https://github.com/mtyaka&entry.752974735=2024-03-11+08:21&entry.1917517419=2024-03-14+08:50&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
