### PR TITLE
docs: Major updates to the README

### PR DESCRIPTION
**Pull request by bradenmacdonald**
As discussed on our last call, I have updated the README to make it much more clear what this project is about and who it can help.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @bradenmacdonald!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by bradenmacdonald** [comment]
@felipemontoya or @MoisesGSalas or @jfavellar90 would one of you like to review this?

**Review by felipemontoya — APPROVED** [review]
Thanks Braden, I think the change to the readme was very necessary.

The file is getting large and in the future we might want to split, but I consider that this should be merged now and we can deal with the larger file later.

**Comment by openedx-webhooks** [comment]
@bradenmacdonald 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-k8s-harmony&entry.867055334=https://github.com/openedx/openedx-k8s-harmony/pull/30&entry.1484655318=https://github.com/bradenmacdonald&entry.752974735=2023-04-07+17:39&entry.1917517419=2023-04-12+01:59&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
